### ISSUE TITLE
Multiple Waypoints (Offset)

### ISSUE THREAD

**Issue by alijabilkis** [imakewebthings/waypoints#155]
Hi, i'm new to javascript. But anyway enjoying your sticky-element-script! :) Unfortunately I can not find out how to give multiple waypoints (offsets) to one object (scrolling in both directions). Just the waypoint on the first place is always shown (no matter which one I write first). As far as I understood, with waypoints 2.0 it is alright to give the position:fixed directly to the object as the sticky-function creates a wrapper around it as a placeholder.

the javascript:

``` js
$(document).ready(function() {
  $('.blau').waypoint('sticky', {
    stuckClass: 'stuck',
    offset:400
  });
  $('.blau').waypoint('sticky', {
    stuckClass: 'stuck2',
    offset:200
  });
});
```

the CSS:

``` css
.blau {
  width:650px;
  height:80px;
  position:fixed;
  bottom:0;
}
.blau.stuck {
  position:absolute;
}
.blau.stuck2 {
  position:fixed;
  top:200px;
}
```
