### ISSUE TITLE
Waypoint side scrolling

### ISSUE THREAD

**Issue by rayplay** [imakewebthings/waypoints#176]
I'm using jquery-waypoints for horizontal content page scrolling. Only my pages content starts at 357px from the top. Now when I scroll to another id the page scrolls left and moves up. 

Maybe somebody can help me out?

HTML (short version):

``` html
<div class="band header">

  <div class="band top"></div>

  <div class="band navigation"></div>

  <div class="band subnav"></div>

</div><!--end header-->

<div class="band content">

  <div id="one" class="panel one"></div>

  <div id="two" class="panel two"></div>

</div><!--end content-->
```

.CSS (short version):

``` css
html {
    margin: 0;
    padding: 0;
    width: 100%;
    overflow-y: visible;
    overflow-x: hidden;
}

body {
    background: #FF0000;
    width: 100%;
}

band.header {
    position: fixed;
    top: 0;
    width: 100%;
    height: 357px;
    z-index: 20;
}

.band.content {
    position: relative;
    margin-top: 357px;
    height: 100%;
}

.band.navigation {
    position: fixed;
    background-color: #FFF;
    top: 235px;
    height: 72px;
    width: 100%;
    z-index: 20;
}
```
