### ISSUE TITLE
Scroll to middle of page and refresh: Previous waypoints called

### ISSUE THREAD

**Issue by mhulse** [imakewebthings/waypoints#310]
Awesome plugin. Thanks!
### CODE:

``` css
.box {
    height: 1000px;
    background: #eee;
    border: 1px solid red;
    margin: 1em 0;
}
```

... and:

``` html
<div id="one" class="box"></div>
<div id="two" class="box"></div>
<div id="three" class="box"></div>
<div id="four" class="box"></div>
```

… and:

``` js
$('.box').waypoint(function(direction) { console.log(direction, this); }, { horizontal: false, offset: '100%' });
```
### Scenario:

When I scroll down page, and have 3 waypoints called (for example) and browser refresh page, all three waypoints get called.
### Problem:

I just need to know the currently visible waypoint. Or, last waypoint (assuming it's the most currently visible).
### Question:

How can I determine the currently visible waypoint? Or, how can I grab the last waypoint in the callback loop?
