### ISSUE TITLE
Remove sticky in mobile view?

### ISSUE THREAD

**Issue by kkashou** [imakewebthings/waypoints#396]
Is there a way to remove sticky plugin in mobile view then when it responds back to desktop it is sticky again?

**Comment by vovayatsyuk** [comment]
I think you can achieve this with css:

```css
@media (max-width:480px) {
    .stuck { position: static; }
}
```
