### ISSUE TITLE
sticky element briefly jumps to top of window

### ISSUE THREAD

**Issue by pinnyp** [imakewebthings/waypoints#68]
When I apply the class of sticky my element scrolls with the window perfectly, but if I scroll back up quickly they will 'jump' to the top of the window before repositioning itself where it started. The code below is part of a larger wrapper with content and sub-content, side-bar etc. I can't really post it all, but any ideas? I have tried using a wrapper div with position:relative for the waypoint and getting the same issue.

``` html
<form method="post" action="">
  <div id="actions" class="actions">
    <input type="reset" class="button" name="reset" value="Reset">
    <input type="button" class="button" name="cancel" value="Cancel">
    <input type="submit" class="button primary" id="save" name="save" value="Save">
   </div>
</form>
```

``` js
<script>
  $.waypoints.settings.scrollThrottle = 30;
  $('.actions').closest('form').waypoint(function(event, direction) {
    $(this).toggleClass('sticky', direction === "down");
    event.stopPropagation();
  });
</script>
```

``` css
form { position: relative; }
.actions { height: 30px; background: #fff; border-bottom: 1px solid #d0d0d0; padding: 5px 0 0 0; margin-bottom: 18px; }
.sticky .actions { position: fixed; top: 0; left: 178px; width: 85.5%; }
```
